INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('USD', 10000, 1);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('USD', 20000, 2);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('USD', 30000, 3);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('USD', 40000, 4);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('BRL', 50004, 1);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('BRL', 100004, 2);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('BRL', 150004, 3);
INSERT INTO PRICE (CURRENCY, PRICE, VEHICLE_ID) VALUES ('BRL', 200004, 4);
